#
# Copyright (c) 2020, Oracle and/or its affiliates. All rights reserved.
# Licensed under the Universal Permissive License v 1.0 as shown at http://oss.oracle.com/licenses/upl.
#

# Default values for oracle-db. Please check README for more information about below parameters

##This parameter changes the ORACLE_SID of the database. The default value is set to FREE (in free edition not changable).
oracle_sid: FREE

##Optional parameter for creating new PDB database. The precreated default database is FREEPDB1.
## It can also be comma separated string for creating multiple PDBs like PDB1,PDB2,PDB3
oracle_database:

## The Oracle Database SYS, SYSTEM and PDB_ADMIN password. Defaults to a randomly generated password
oracle_password:

## The application username. Default is free.
app_user: free

## The application user password. Defaults to a randomly generated password
app_user_password:

## Oracle client character set
nls_lang: AMERICAN_AMERICA.AL32UTF8

## The character set to use during db creation. Defaults to AMERICAN_AMERICA.AL32UTF8
oracle_characterset: AL32UTF8

## The database edition (default: free)
oracle_edition: free

## Enable archive log mode when creating the database
enable_archivelog: false

## Enable persistence using Persistent Volume Claims
## ref: http://kubernetes.io/docs/user-guide/persistent-volumes/
## Override 'persistence' to 'null' using '--set' option, if persistence is not desired
persistence:
  ## Oracle Database data Persistent Volume Storage Class
  storageClass: ""
  size: 50Gi

## Deploy only on nodes in a particular availability domain
## Leave empty if there is no such requirement
availabilityDomain:

podSecurityContext:
  runAsNonRoot: true
  seccompProfile:
    type: RuntimeDefault

securityContext:
  allowPrivilegeEscalation: false
  capabilities:
    drop:
      - ALL
  readOnlyRootFilesystem: false

resources:
  requests:
    cpu: 500m
    memory: 1Gi
    ephemeral-storage: 1Gi
  limits:
    cpu: 2
    memory: 3Gi
    ephemeral-storage: 1Gi

## Deploy multiple replicas for fast fail over
## If 'persistence' is 'null' then fast fail over will not happen even if replicas>1 (as no persistence)
replicas: 1

## Deploy LoadBalancer service
loadBalService: false

## Image vendor. Can be gvenzl or oracle
image_vendor: gvenzl

## Name of image. gvenzl is default
## image: container-registry.oracle.com/database/free:latest
image: gvenzl/oracle-free:latest

## Image pull policy, IfNotPresent or Always
imagePullPolicy: IfNotPresent

## Container registry login/password
imagePullSecrets:

## Deploy only on nodes having required labels .
## Format label_name : label_value . eg pool: sidb
## Leave empty if there is no such requirement
nodeLabels:
#  pool: sidb
